name: Cypress Tests
on:
  pull_request:
    branches:
      - main

jobs:
  cypress-electron-tests:
    runs-on: cypress/browsers:node-18.16.0-chrome-113.0.5672.126
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: npm install

      - name: Run E2E tests
        run: npx cypress run


      

